version: "3.9"
services:
    db:
        image: "postgres:13.2"
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "Your_password123"
    browser:
        image: "selenium/standalone-firefox"
        ports:
            - 4446:4444
        volumes: 
            - ./browser-data:/dev/shm